language: cpp
sudo: required
dist: bionic
compiler:
  - gcc
os:
  - linux

branches:
  only:
  - master

install:
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir ${DEPS_DIR} && cd ${DEPS_DIR}
  - travis_retry wget --no-check-certificate https://cmake.org/files/v3.18/cmake-3.18.0-rc1-Linux-x86_64.tar.gz
  # this is optional, but useful:
  # do a quick md5 check to ensure that the archive we downloaded did not get compromised
  - echo "33b07e7e255555fa3bf64ae591b24e4f *cmake-3.18.0-rc1-Linux-x86_64.tar.gz" > cmake_md5.txt
  - md5sum -c cmake_md5.txt
  - tar -xvf cmake-3.18.0-rc1-Linux-x86_64.tar.gz > /dev/null
  - mv cmake-3.18.0-rc1-Linux-x86_64 cmake-install
  - PATH=${DEPS_DIR}/cmake-install:${DEPS_DIR}/cmake-install/bin:$PATH
  - cd ${TRAVIS_BUILD_DIR}

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - make
  - make test